services:
  my_doctor_db:
    image: postgres:13
    container_name: my_doctor_db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    env_file:
      - .env
    networks:
      - my_doctor_network

  my_doctor:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    container_name: my_doctor
    command: sh ./scripts/dev-start.sh
    depends_on:
      my_doctor_db:
        condition: service_healthy
    ports:
      - "${PHX_PORT}:4000"
    volumes:
      - .:/app
      - deps_cache:/app/deps
      - build_cache:/app/_build
    env_file:
      - .env
    networks:
      - my_doctor_network
    stdin_open: true
    tty: true

networks:
  my_doctor_network:

volumes:
  postgres_data:
  deps_cache:
  build_cache:
